# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    steps:
      - checkout

      # Install docs & dependencies.
      - run: npm run install-docs

      # Build & Deploy the docs.
      - run: npm run docs-deploy
